# Generated by Django 4.0.4 on 2022-05-10 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='postsmodels',
            name='author',
        ),
        migrations.DeleteModel(
            name='FollowersModels',
        ),
        migrations.AlterField(
            model_name='postsmodels',
            name='like',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.likemodels'),
        ),
    ]
