# Generated by Django 4.0.4 on 2022-05-10 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_likemodels_remove_usermodels_posts_postsmodels_and_more'),
        ('posts', '0002_likemodels_remove_postsmodels_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsmodels',
            name='like',
        ),
        migrations.DeleteModel(
            name='LikeModels',
        ),
        migrations.DeleteModel(
            name='PostsModels',
        ),
    ]
