# Generated by Django 4.0.4 on 2022-05-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_likemodels_remove_usermodels_posts_postsmodels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodels',
            name='like',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='LikeModels',
        ),
    ]
