# Generated by Django 4.0.4 on 2022-05-10 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_postsmodels_slug_alter_usermodels_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodels',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
