# Generated by Django 4.0.4 on 2022-05-10 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_postsmodels_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodels',
            name='like',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='following',
            field=models.ManyToManyField(null=True, related_name='follower', to='accounts.usermodels'),
        ),
    ]
