# Generated by Django 4.0.4 on 2022-05-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_postsmodels_like_alter_usermodels_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='follower', to='accounts.usermodels'),
        ),
    ]
