# Generated by Django 4.0.4 on 2022-05-12 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_usermodels_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodels',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='accounts.usermodels'),
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='following',
            field=models.ManyToManyField(null=True, related_name='follower', to='accounts.usermodels'),
        ),
    ]
